### ISSUE TITLE
Create README including the features of the app and details of app with some screenshots.

### ISSUE THREAD

**Issue by golupankajgoyal** [golupankajgoyal/CustomerRegistration#1]

**Comment by sfxjolugbohunmi** [comment]
@golupankajgoyal Kindly assign this to me
Also, kindly add the hacktoberfest topic to this repository

**Comment by golupankajgoyal** [comment]
@sfxjolugbohunmi Thanks for picking this up. Looking forward to your PR.
Here is the overview of the application: 
[CustomerRegistration Report (1).pdf](https://github.com/golupankajgoyal/CustomerRegistration/files/5360645/CustomerRegistration.Report.1.pdf)

Please refer to these repos on how to structure the README:
Cognitia 2018 Android App: https://github.com/NIT-Meghalaya/Cognitia-2018-App
RESTFUL-Blog-App : https://github.com/GovindCodes/RESTful-Blog-APP/blob/master/README.md

**Comment by mayorjay** [comment]
@golupankajgoyal Thanks
This is still sfxjolugbohunmi (you can check my name)
I'll be creating the PR with this my personal GitHub account

**Comment by mayorjay** [comment]
@golupankajgoyal Please what's the link to this App on Google Play store?

**Comment by golupankajgoyal** [comment]
@mayorJAY Here is the link of this app on Google play.

https://play.google.com/store/apps/details?id=com.digiflying.customerregistration

**Comment by golupankajgoyal** [comment]
Well done @mayorJAY 
Great Work
